// Shared helpers for the 09-higgsfield parametric variant generator.
// Every generated card is a standalone HyperFrames sub-composition meeting the
// card contract: root div w/ composition attrs, one paused GSAP timeline keyed
// by composition id, tokens.css vars only, data-slot text, deterministic.

/** Seeded LCG — determinism rule: no Math.random anywhere in the pipeline. */
export function lcg(seed) {
  let s = seed >>> 0;
  return () => {
    s = (s * 1103515245 + 12345) % 2147483648;
    return s / 2147483648;
  };
}

/** Seeded shuffle (Fisher-Yates). */
export function shuffle(arr, rnd) {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rnd() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

/** Cartesian product of axis arrays: [{k:v},...] combos. */
export function combos(axes) {
  let out = [{}];
  for (const [key, values] of Object.entries(axes)) {
    const next = [];
    for (const base of out) for (const v of values) next.push({ ...base, [key]: v });
    out = next;
  }
  return out;
}

/** The standalone card HTML shell. js runs with `root` + `tl` predefined;
    it must add tweens to tl. Timeline is registered paused on window.__timelines. */
export function shell({ id, comment, css, body, js, depth = "../../.." }) {
  return `<!doctype html>
<!--
  HIGGSFIELD · generated variant · ${id}
  ${comment}
  GENERATED by scripts/style-library/gen-higgsfield-variants.mjs - do not hand-edit;
  edit the template family + re-run the generator.
-->
<html>
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="${depth}/tokens.css" />
    <style>
      html, body { margin: 0; background: transparent; }
      #${id} {
        position: absolute; inset: 0; width: 1920px; height: 1080px;
        overflow: hidden; font-family: var(--font-display);
      }
${css}
    </style>
  </head>
  <body>
    <div id="${id}" data-composition-id="${id}" data-start="0" data-width="1920" data-height="1080">
${body}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <script>
      window.__timelines = window.__timelines || {};
      const root = "#${id}";
      const cssv = getComputedStyle(document.documentElement);
      const LIME = cssv.getPropertyValue("--lime").trim();
      const LIMESOFT = cssv.getPropertyValue("--lime-soft").trim();
      const WHITE = cssv.getPropertyValue("--white").trim();
      function splitChars(el) {
        if (!el) return;
        const text = el.textContent; el.textContent = "";
        text.split("").forEach((ch) => {
          const s = document.createElement("span");
          s.className = "ch"; s.textContent = ch === " " ? "\\u00A0" : ch;
          el.appendChild(s);
        });
      }
      function seededOrder(n, seed) {
        let s = seed; const idx = Array.from({ length: n }, (_, i) => i);
        for (let i = n - 1; i > 0; i--) {
          s = (s * 1103515245 + 12345) % 2147483648;
          const j = s % (i + 1); [idx[i], idx[j]] = [idx[j], idx[i]];
        }
        const rank = new Array(n); idx.forEach((v, i) => (rank[v] = i)); return rank;
      }
      const tl = gsap.timeline({ paused: true });
${js}
      window.__timelines["${id}"] = tl;
    </script>
  </body>
</html>
`;
}

/* ---- shared visual fragments ------------------------------------------- */

/** tier1 canvas background layers + css. kind: navy | olive | cream */
export function canvasLayers(rootId, kind, opts = {}) {
  const warmSide = opts.warmSide ?? "right"; // warm creep corner for navy
  if (kind === "navy") {
    return {
      css: `      #${rootId} { background: linear-gradient(180deg, var(--navy-2) 0%, var(--navy) 46%); }
      #${rootId} .bg-streaks { position: absolute; inset: 0; background: var(--streaks); }
      #${rootId} .bg-warm { position: absolute; inset: 0; opacity: 0;
        background: radial-gradient(60% 55% at ${warmSide === "left" ? "8%" : "92%"} 100%, rgba(120, 62, 18, 0.5) 0%, transparent 70%); }
      #${rootId} .bg-vig { position: absolute; inset: 0; background: var(--vignette); }`,
      body: `      <div class="bg-streaks"></div><div class="bg-warm"></div><div class="bg-vig"></div>`,
      js: `      tl.to(root + " .bg-warm", { opacity: 1, duration: 1.6, ease: "sine.inOut" }, 1.0);`,
    };
  }
  if (kind === "olive") {
    return {
      css: `      #${rootId} { background: var(--olive); }
      #${rootId} .bg-bokeh { position: absolute; inset: -6%; width: 112%; height: 112%;
        background: var(--olive-bokeh); filter: blur(46px); }
      #${rootId} .bg-dots { position: absolute; inset: 0;
        background-image: var(--dot-grid); background-size: var(--dot-grid-size); }
      #${rootId} .bg-vig { position: absolute; inset: 0; background: var(--vignette); }`,
      body: `      <div class="bg-bokeh"></div><div class="bg-dots"></div><div class="bg-vig"></div>`,
      js: `      tl.to(root + " .bg-bokeh", { xPercent: 1.5, yPercent: -1.1, duration: 3.4, ease: "sine.inOut" }, 0);`,
    };
  }
  // cream
  return {
    css: `      #${rootId} { background: linear-gradient(180deg, var(--cream-2) 0%, var(--cream) 60%); }`,
    body: ``,
    js: ``,
  };
}

/** Glass panel CSS for a .panel > .tilt structure (GSAP moves .panel, static
    3D tilt lives on .tilt). side: left | right. lit: light glass vs dark glass. */
export function glassCss(rootId, { side = "right", lit = false, top = 190, width = 560, pad = "44px 50px" }) {
  const tilt = side === "left" ? "var(--glass-tilt-l)" : "var(--glass-tilt)";
  const anchor = side === "left" ? `left: 120px;` : `right: 120px;`;
  return `      #${rootId} .panel { position: absolute; top: ${top}px; ${anchor} z-index: 3; }
      #${rootId} .tilt {
        width: ${width}px; padding: ${pad};
        display: flex; flex-direction: column; gap: 20px;
        background: ${lit ? "var(--glass-bg-lit)" : "var(--glass-bg)"};
        border: var(--glass-edge); border-radius: var(--radius);
        backdrop-filter: var(--glass-blur); -webkit-backdrop-filter: var(--glass-blur);
        box-shadow: var(--glass-shadow);
        transform: ${tilt};
      }`;
}

/** Entrance tween JS for a selector. kind: slide-side | rise | pop | blur */
export function entranceJs(sel, kind, side = "right", t = 0.1) {
  const x = side === "left" ? -90 : 90;
  switch (kind) {
    case "rise": return `      tl.from(root + " ${sel}", { autoAlpha: 0, y: 70, duration: 0.55, ease: "expo.out" }, ${t});`;
    case "pop": return `      tl.from(root + " ${sel}", { autoAlpha: 0, scale: 0.82, duration: 0.5, ease: "back.out(1.9)" }, ${t});`;
    case "blur": return `      tl.from(root + " ${sel}", { autoAlpha: 0, filter: "blur(14px)", duration: 0.6, ease: "power2.out" }, ${t});`;
    default: return `      tl.from(root + " ${sel}", { autoAlpha: 0, x: ${x}, duration: 0.55, ease: "expo.out" }, ${t});`;
  }
}

/** Drift-while-alive JS for a selector (the glass signature). */
export function driftJs(sel, { amp = 10, rot = 0.6, t = 0.7 } = {}) {
  return `      tl.to(root + " ${sel}", { y: ${-amp}, rotation: ${rot}, duration: 3, ease: "sine.inOut", yoyo: true, repeat: 1 }, ${t});`;
}

/** Hold to a total duration. */
export function holdJs(sec) {
  return `      tl.set({}, {}, ${sec});`;
}
